

import React, { useState, useMemo, useCallback } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import Select from "react-select";


async function loadData() {
    try {
        const response = await fetch('/data/agereport_sample.json');
        if (!response.ok) throw new Error('Network response was not ok');
        console.log(response[1])
        const data = await response.json()
        return data


    } catch (error) {
        console.error('Error reading JSON:', error);
    }

}
const SAMPLE_DATA = await loadData();

const TOWERS = {
    "ROYAL RESIDENCE 1 key ": "ROYAL RESIDENCE 1 ",
    "ROYAL RESIDENCE 2 key ": "ROYAL RESIDENCE 2 ",
    "ROYAL RESIDENCE 3 key": "ROYAL RESIDENCE 3 "
};

const COLUMNS = [
    { key: "UnitNumber", label: "Unit No.", type: "text" },
    { key: "AccountNumber", label: "Account No.", type: "text" },
    { key: "CustomerName", label: "Customer Name", type: "text" },
    { key: "ZeroToThirty", label: "Zero To Thirty", type: "money" },
    { key: "ThirtyToSixty", label: "Thirty One To Sixty", type: "money" },
    { key: "SixtyToNinty", label: "Sixty One To Ninety", type: "money" },
    { key: "NintyToOneEighty", label: "Ninety One To One Eighty", type: "money" },
    { key: "OneEightyPlus", label: "One Eighty Plus", type: "money" },
    { key: "TotalAmount", label: "Total Amount", type: "total" },
];


/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */
const fmt = (n) =>
    (Number(n) || 0).toLocaleString("en-US", {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    });

const isoToApiDate = (iso) => {
    const [y, m, d] = iso.split("-");
    return `${m}/${d}/${y}`;
};

function sumTotals(rows) {
    return rows.reduce(
        (acc, r) => {
            acc.ZeroToThirty += r.ZeroToThirty;
            acc.ThirtyToSixty += r.ThirtyToSixty;
            acc.SixtyToNinty += r.SixtyToNinty;
            acc.NintyToOneEighty += r.NintyToOneEighty;
            acc.OneEightyPlus += r.OneEightyPlus;
            acc.TotalAmount += r.TotalAmount;
            return acc;
        },
        {
            ZeroToThirty: 0,
            ThirtyToSixty: 0,
            SixtyToNinty: 0,
            NintyToOneEighty: 0,
            OneEightyPlus: 0,
            TotalAmount: 0,
        }
    );
}


export default function AgingReport({ fetchData }) {
    const [tower, setTower] = useState(Object.keys(TOWERS)[0]);
    const [toDate, setToDate] = useState("2026-07-07");
    const [data, setData] = useState(SAMPLE_DATA);
    const [loading, setLoading] = useState(false);

    const apiDate = isoToApiDate(toDate);
    const generatedBy = data[0]?.GeneratedBy || "—";
    const uom = data[0]?.TotalAmountUOM || "AED";

    const totals = useMemo(() => sumTotals(data), [data]);

    const handleGenerate = useCallback(async () => {
        if (!fetchData) {
            setData(SAMPLE_DATA);
            return;
        }
        setLoading(true);
        try {
            const result = await fetchData(tower, apiDate);
            setData(Array.isArray(result) ? result : []);
        } catch (err) {
            console.error("Failed to load aging report:", err);
        } finally {
            setLoading(false);
        }
    }, [fetchData, tower, apiDate]);

    const handleExportPdf = useCallback(() => {
        const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
        const pageWidth = doc.internal.pageSize.getWidth();

        doc.setFontSize(13);
        doc.setFont(undefined, "bold");
        doc.setTextColor(16, 36, 61);
        doc.text(`${TOWERS[tower]} Aging Report till ${apiDate}`, pageWidth / 2, 40, { align: "center" });

        doc.setFontSize(9);
        doc.setFont(undefined, "normal");
        doc.setTextColor(90, 105, 120);
        doc.text(`Generated On: ${apiDate}`, 40, 62);
        doc.text(`Generated By: ${generatedBy}`, pageWidth - 40, 62, { align: "right" });

        const head = [COLUMNS.map((c) => c.label)];
        const body = data.map((r) =>
            COLUMNS.map((c) => (c.type === "text" ? r[c.key] : fmt(r[c.key])))
        );
        body.push([
            "Totals",
            "",
            "",
            fmt(totals.ZeroToThirty),
            fmt(totals.ThirtyToSixty),
            fmt(totals.SixtyToNinty),
            fmt(totals.NintyToOneEighty),
            fmt(totals.OneEightyPlus),
            `${fmt(totals.TotalAmount)} ${uom}`,
        ]);

        autoTable(doc, {
            head,
            body,
            startY: 76,
            styles: { fontSize: 8.5, cellPadding: 5, lineColor: [221, 227, 234], lineWidth: 0.5 },
            headStyles: { fillColor: [234, 241, 251], textColor: [16, 36, 61], fontStyle: "bold" },
            columnStyles: {
                0: { halign: "left" },
                1: { halign: "left" },
                2: { halign: "left" },
                3: { halign: "right" },
                4: { halign: "right" },
                5: { halign: "right" },
                6: { halign: "right" },
                7: { halign: "right" },
                8: { halign: "right", fontStyle: "bold" },
            },
            alternateRowStyles: { fillColor: [249, 251, 253] },
            didParseCell: (cellData) => {
                if (cellData.row.index === body.length - 1 && cellData.section === "body") {
                    cellData.cell.styles.fillColor = [234, 241, 251];
                    cellData.cell.styles.fontStyle = "bold";
                }
            },
        });

        doc.save(`Aging_Report_${tower.replace(/\s+/g, "_")}_${apiDate.replace(/\//g, "-")}.pdf`);
    }, [data, tower, apiDate, generatedBy, totals, uom]);

    const handleExportXlsx = useCallback(() => {
        const header = COLUMNS.map((c) => c.label);
        const rows = data.map((r) => COLUMNS.map((c) => (c.type === "text" ? r[c.key] : Number(r[c.key]))));

        const aoa = [
            [`${TOWERS[tower]} Aging Report till ${apiDate}`],
            [`Generated On: ${apiDate}`, "", "", "", "", "", "", `Generated By: ${generatedBy}`],
            [],
            header,
            ...rows,
            [
                "Totals",
                "",
                "",
                totals.ZeroToThirty,
                totals.ThirtyToSixty,
                totals.SixtyToNinty,
                totals.NintyToOneEighty,
                totals.OneEightyPlus,
                totals.TotalAmount,
            ],
        ];

        const ws = XLSX.utils.aoa_to_sheet(aoa);
        ws["!cols"] = [
            { wch: 10 },
            { wch: 14 },
            { wch: 24 },
            { wch: 13 },
            { wch: 16 },
            { wch: 16 },
            { wch: 18 },
            { wch: 14 },
            { wch: 14 },
        ];
        ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 8 } }];

        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, "Aging Report");
        XLSX.writeFile(wb, `Aging_Report_${tower.replace(/\s+/g, "_")}_${apiDate.replace(/\//g, "-")}.xlsx`);
    }, [data, tower, apiDate, generatedBy, totals]);

    let prevUnit = null;

    return (
        <div style={styles.app}>
            {/* Toolbar */}
            <div style={styles.toolbar}>
                <div style={styles.controls}>
                    <div style={styles.field}>
                        <label style={styles.label}>Tower Name</label>
                        <Select
                            value={{
                                label: TOWERS[tower],
                                value: tower,
                            }}
                            onChange={(selected) => setTower(selected.value)}
                            options={Object.keys(TOWERS).map((t) => ({
                                label: TOWERS[t],
                                value: t,
                            }))}
                            isSearchable={true}
                            placeholder="Search Tower..."
                            styles={{
                                control: (base) => ({
                                    ...base,
                                    ...styles.input,
                                    minHeight: "36px",
                                    width: "220px",
                                }),
                                menu: (base) => ({
                                    ...base,
                                    zIndex: 9999,
                                }),
                            }}
                        />
                    </div>
                    <div style={styles.field}>
                        <label style={styles.label}>To Date</label>
                        <input
                            style={styles.input}
                            type="date"
                            value={toDate}
                            onChange={(e) => setToDate(e.target.value)}
                        />
                    </div>
                    <button style={styles.btnPrimary} onClick={handleGenerate} disabled={loading}>
                        {loading ? "Loading…" : "⟳ Generate Report"}
                    </button>
                </div>
            </div>

            {/* Export bar */}
            <div style={styles.exportBar}>
                <div style={styles.statusLine}>
                    Showing live data · {data.length} line item{data.length === 1 ? "" : "s"}
                </div>
                <div style={styles.exportActions}>
                    <button style={styles.btnExport} onClick={handleExportPdf}>
                        Export PDF
                    </button>
                    <button style={styles.btnExport} onClick={handleExportXlsx}>
                        Export Excel
                    </button>
                </div>
            </div>

            {/* Report sheet / HTML preview */}
            <div style={styles.sheet}>
                <div style={styles.sheetInner}>
                    <div style={styles.reportTitle}>{`${TOWERS[tower]} Aging Report till ${apiDate}`}</div>
                    <div style={styles.reportMeta}>
                        <span>
                            Generated On: <b>{apiDate}</b>
                        </span>
                        <span>
                            Generated By: <b>{generatedBy}</b>
                        </span>
                    </div>

                    {data.length === 0 ? (
                        <div style={styles.empty}>No records for the selected tower and date.</div>
                    ) : (
                        <table style={styles.table}>
                            <thead>
                                <tr>
                                    {COLUMNS.map((c) => (
                                        <th
                                            key={c.key}
                                            style={{
                                                ...styles.th,
                                                textAlign: c.type === "text" ? "left" : "right",
                                            }}
                                        >
                                            {c.label}
                                        </th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody>
                                {data.map((r, i) => {
                                    const isNewGroup = prevUnit !== null && prevUnit !== r.UnitNumber;
                                    prevUnit = r.UnitNumber;
                                    return (
                                        <tr key={r.ServiceAgreementKey || i} style={i % 2 === 1 ? styles.rowAlt : undefined}>
                                            {COLUMNS.map((c) => {
                                                const value = r[c.key];
                                                const isText = c.type === "text";
                                                let color = "#1b2733";
                                         
                                                return (
                                                    <td
                                                        key={c.key}
                                                        style={{
                                                            ...styles.td,
                                                            textAlign: isText ? "left" : "right",
                                                            color,
                                                            fontWeight: c.type === "total" ? 700 : 400,
                                                            borderTop: isNewGroup ? "1.5px solid #c7d3de" : styles.td.borderTop,
                                                        }}
                                                    >
                                                        {isText ? value : fmt(value)}
                                                    </td>
                                                );
                                            })}
                                        </tr>
                                    );
                                })}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td style={styles.tfootTd}>Totals</td>
                                    <td style={styles.tfootTd} />
                                    <td style={styles.tfootTd} />
                                    <td style={{ ...styles.tfootTd, textAlign: "right" }}>{fmt(totals.ZeroToThirty)}</td>
                                    <td style={{ ...styles.tfootTd, textAlign: "right" }}>{fmt(totals.ThirtyToSixty)}</td>
                                    <td style={{ ...styles.tfootTd, textAlign: "right" }}>{fmt(totals.SixtyToNinty)}</td>
                                    <td style={{ ...styles.tfootTd, textAlign: "right" }}>{fmt(totals.NintyToOneEighty)}</td>
                                    <td style={{ ...styles.tfootTd, textAlign: "right" }}>{fmt(totals.OneEightyPlus)}</td>
                                    <td style={{ ...styles.tfootTd, textAlign: "right" }}>
                                        {fmt(totals.TotalAmount)} {uom}
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    )}
                </div>
            </div>
        </div>
    );
}


const styles = {
    app: {
        maxWidth: 900,
        margin: "0 auto",
        padding: "20px 20px 60px",
        fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
        color: "#1b2733",
        background: "#f2f5f8",
    },
    toolbar: {
        padding: "16px 20px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 16,
        flexWrap: "wrap",
    },
    toolbarTitle: {
        color: "#fff",
        fontSize: 17,
        fontWeight: 600,
        margin: 0,
    },
    controls: { display: "flex", alignItems: "flex-end", gap: 14, flexWrap: "wrap" },
    field: { display: "flex", flexDirection: "column", gap: 4 },
    label: {
        fontSize: 10.5,
        textTransform: "uppercase",
        letterSpacing: "0.06em",
        fontWeight: 600,
    },
    input: {
        border: "1px solid #35516f",
        padding: "7px 10px",
        fontSize: 13,
        minWidth: 170,
        outline: "none",
    },
    btnPrimary: {
        border: "1px solid #35516f",
        padding: "8px 16px",
        fontSize: 13,
        fontWeight: 600,
        cursor: "pointer",
    },
    exportBar: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        margin: "16px 0 0",
        padding: "10px 4px",
        flexWrap: "wrap",
        gap: 10,
    },
    statusLine: { fontSize: 12, color: "#5b6b7b" },
    exportActions: { display: "flex", gap: 10 },
    btnExport: {
        background: "#fff",
        border: "1px solid #dde3ea",
        padding: "8px 14px",
        fontSize: 12.5,
        fontWeight: 600,
        cursor: "pointer",
    },
  sheet: {
    background: "#fff",
    marginTop: 14,
    border: "1px solid #dde3ea",
    overflowX: "auto",
},

sheetInner: { 
    padding: "24px 20px 28px" 
},    reportTitle: {
        textAlign: "center",
        fontSize: 17,
        fontWeight: 700,
        color: "#10243d",
        marginBottom: 18,
    },
    reportMeta: {
        display: "flex",
        justifyContent: "space-between",
        fontSize: 12,
        color: "#5b6b7b",
        marginBottom: 16,
    },
    table: { width: "100%", borderCollapse: "collapse", fontSize: 12.5 },
 th: {
    background: "#eaf1fb",
    color: "#10243d",
    fontWeight: 700,
    fontSize: 11.5,
    padding: "9px 10px",
    border: "1px solid #dde3ea",
    whiteSpace: "normal",
},
    td: { padding: "8px 10px", border: "1px solid #dde3ea" },
    rowAlt: { background: "#f9fbfd" },
    tfootTd: {
        padding: "11px 10px",
        border: "1px solid #dde3ea",
        borderTop: "2px solid #10243d",
        background: "#eaf1fb",
        fontWeight: 700,
        color: "#10243d",
    },
    empty: { textAlign: "center", padding: "40px 0", color: "#5b6b7b", fontSize: 13 },
};