

import React, { useState, useMemo, useCallback } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import Select from "react-select";


async function loadData() {
    try {
        const response = await fetch('/data/payment_summary_data.json');
        if (!response.ok) throw new Error('Network response was not ok');
        console.log(response[1])
        const data = await response.json()
        return data


    } catch (error) {
        console.error('Error reading JSON:', error);
    }

}
const SAMPLE_DATA = await loadData();
const TOWERS = {
    "ROYAL RESIDENCE 1 key ": "ROYAL RESIDENCE 1",
    "ROYAL RESIDENCE 2 key ": "ROYAL RESIDENCE 2",
    "ROYAL RESIDENCE 3 key": "ROYAL RESIDENCE 3"
};
const COLUMNS = [
  { key: "UnitNumber", label: "Unit No.", type: "text" },
  { key: "SecurityDeposite", label: "Security Deposit (AED)", type: "money" },
  { key: "OpeningBalance", label: "Opening Balance (AED)", type: "money" },
  { key: "PreviousBalance", label: "Previous Balance (AED)", type: "money" },
  { key: "ConsumptionFuelSubCharges", label: "Consumption Fuel Sub Charges (AED)", type: "money" },
  { key: "CapacityDemandCharges", label: "Capacity Demand Charges (AED)", type: "money" },
  { key: "BillingFee", label: "Billing Fee (AED)", type: "money" },
  { key: "OtherFee", label: "Other Fee (AED)", type: "money" },
  { key: "ReceptionAmount", label: "Reception Amount (AED)", type: "money" },
  { key: "AdvanceAmount", label: "Advance Amount (AED)", type: "money" },
  { key: "OutstandingAmount", label: "Outstanding Amount (AED)", type: "total" },
];

const SUM_KEYS = [
  "SecurityDeposite",
  "OpeningBalance",
  "PreviousBalance",
  "ConsumptionFuelSubCharges",
  "CapacityDemandCharges",
  "BillingFee",
  "OtherFee",
  "ReceptionAmount",
  "AdvanceAmount",
  "OutstandingAmount",
];

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */
const fmt = (n) =>
  (Number(n) || 0).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

const isoToApiDate = (iso) => {
  const [y, m, d] = iso.split("-");
  return `${m}/${d}/${y}`;
};

const cellValue = (col, row) => (col.type === "text" ? row[col.key] : fmt(row[col.key]));

function sumTotals(rows) {
  const totals = {};
  SUM_KEYS.forEach((k) => (totals[k] = 0));
  rows.forEach((r) => SUM_KEYS.forEach((k) => (totals[k] += Number(r[k]) || 0)));
  return totals;
}

/* ------------------------------------------------------------------ */
/* Component                                                           */
/* ------------------------------------------------------------------ */
export default function PaymentSummaryReport({ fetchData }) {
  const [tower, setTower] = useState(Object.keys(TOWERS)[0]);
  const [toDate, setToDate] = useState("2026-07-10");
  const [data, setData] = useState(SAMPLE_DATA);
  const [loading, setLoading] = useState(false);

  const apiDate = isoToApiDate(toDate);
  const generatedBy = data[0]?.GeneratedBy || "—";
  const generatedOn = data[0]?.GeneratedOn || apiDate;

  const totals = useMemo(() => sumTotals(data), [data]);

  const handleGenerate = useCallback(async () => {
    if (!fetchData) {
      setData(SAMPLE_DATA);
      return;
    }
    setLoading(true);
    try {
      const result = await fetchData(tower, apiDate);
      setData(Array.isArray(result) ? result : []);
    } catch (err) {
      console.error("Failed to load payment summary report:", err);
    } finally {
      setLoading(false);
    }
  }, [fetchData, tower, apiDate]);

  const handleExportPdf = useCallback(() => {
    const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFontSize(13);
    doc.setFont(undefined, "bold");
    doc.setTextColor(16, 36, 61);
    doc.text(`${TOWERS[tower]} Payment Summary Report till ${apiDate}`, pageWidth / 2, 40, { align: "center" });

    doc.setFontSize(9);
    doc.setFont(undefined, "normal");
    doc.setTextColor(90, 105, 120);
    doc.text(`Generated On: ${generatedOn}`, 40, 62);
    doc.text(`Generated By: ${generatedBy}`, pageWidth - 40, 62, { align: "right" });

    const head = [COLUMNS.map((c) => c.label)];
    const body = data.map((r) => COLUMNS.map((c) => cellValue(c, r)));

    const footRow = COLUMNS.map((c, i) => {
      if (i === 0) return "Totals";
      if (c.key === "OutstandingAmount") return fmt(totals.OutstandingAmount);
      return fmt(totals[c.key]);
    });
    body.push(footRow);

    const columnStyles = {};
    COLUMNS.forEach((c, i) => {
      columnStyles[i] = { halign: c.type === "text" ? "left" : "right" };
      if (c.type === "total") columnStyles[i].fontStyle = "bold";
    });

    autoTable(doc, {
      head,
      body,
      startY: 76,
      styles: { fontSize: 8, cellPadding: 5, lineColor: [221, 227, 234], lineWidth: 0.5 },
      headStyles: { fillColor: [234, 241, 251], textColor: [16, 36, 61], fontStyle: "bold", fontSize: 8 },
      columnStyles,
      alternateRowStyles: { fillColor: [249, 251, 253] },
      didParseCell: (cellData) => {
        if (cellData.row.index === body.length - 1 && cellData.section === "body") {
          cellData.cell.styles.fillColor = [234, 241, 251];
          cellData.cell.styles.fontStyle = "bold";
        }
      },
    });

    doc.save(`Payment_Summary_Report_${tower.replace(/\s+/g, "_")}_${apiDate.replace(/\//g, "-")}.pdf`);
  }, [data, tower, apiDate, generatedBy, generatedOn, totals]);

  const handleExportXlsx = useCallback(() => {
    const header = COLUMNS.map((c) => c.label);
    const rows = data.map((r) => COLUMNS.map((c) => (c.type === "text" ? r[c.key] : Number(r[c.key]))));

    const footRow = COLUMNS.map((c, i) => (i === 0 ? "Totals" : totals[c.key]));

    const aoa = [
      [`${TOWERS[tower]} Payment Summary Report till ${apiDate}`],
      [
        `Generated On: ${generatedOn}`,
        ...Array(COLUMNS.length - 2).fill(""),
        `Generated By: ${generatedBy}`,
      ],
      [],
      header,
      ...rows,
      footRow,
    ];

    const ws = XLSX.utils.aoa_to_sheet(aoa);
    ws["!cols"] = COLUMNS.map((c) => ({ wch: c.type === "text" ? 12 : 18 }));
    ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: COLUMNS.length - 1 } }];

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Payment Summary Report");
    XLSX.writeFile(wb, `Payment_Summary_Report_${tower.replace(/\s+/g, "_")}_${apiDate.replace(/\//g, "-")}.xlsx`);
  }, [data, tower, apiDate, generatedBy, generatedOn, totals]);

  return (
    <div style={styles.app}>
      {/* Toolbar */}
      <div style={styles.toolbar}>
        <div style={styles.controls}>
          <div style={styles.field}>
            <label style={styles.label}>Tower Name</label>
            <Select
                            value={{
                                label: TOWERS[tower],
                                value: tower,
                            }}
                            onChange={(selected) => setTower(selected.value)}
                            options={Object.keys(TOWERS).map((t) => ({
                                label: TOWERS[t],
                                value: t,
                            }))}
                            isSearchable={true}
                            placeholder="Search Tower..."
                            styles={{
                                control: (base) => ({
                                    ...base,
                                    ...styles.input,
                                    minHeight: "36px",
                                    width: "220px",
                                }),
                                menu: (base) => ({
                                    ...base,
                                    zIndex: 9999,
                                }),
                            }}
                        />
          </div>
          <div style={styles.field}>
            <label style={styles.label}>To Date</label>
            <input style={styles.input} type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} />
          </div>
          <button style={styles.btnPrimary} onClick={handleGenerate} disabled={loading}>
            {loading ? "Loading…" : "⟳ Generate Report"}
          </button>
        </div>
      </div>

      {/* Export bar */}
      <div style={styles.exportBar}>
        <div style={styles.statusLine}>
          Showing live data · {data.length} line item{data.length === 1 ? "" : "s"}
        </div>
        <div style={styles.exportActions}>
          <button style={styles.btnExport} onClick={handleExportPdf}>
             Export PDF
          </button>
          <button style={styles.btnExport} onClick={handleExportXlsx}>
             Export Excel
          </button>
        </div>
      </div>

      {/* Report sheet / HTML preview */}
      <div style={styles.sheet}>
        <div style={styles.sheetInner}>
          <div style={styles.reportTitle}>{`${TOWERS[tower]} Payment Summary Report till ${apiDate}`}</div>
          <div style={styles.reportMeta}>
            <span>
              Generated On: <b>{generatedOn}</b>
            </span>
            <span>
              Generated By: <b>{generatedBy}</b>
            </span>
          </div>

          {data.length === 0 ? (
            <div style={styles.empty}>No records for the selected tower and date.</div>
          ) : (
            <table style={styles.table}>
              <thead>
                <tr>
                  {COLUMNS.map((c) => (
                    <th
                      key={c.key}
                      style={{
                        ...styles.th,
                        textAlign: c.type === "text" ? "left" : "right",
                      }}
                    >
                      {c.label}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {data.map((r, i) => (
                  <tr key={r.UnitID || i} style={i % 2 === 1 ? styles.rowAlt : undefined}>
                    {COLUMNS.map((c) => (
                      <td
                        key={c.key}
                        style={{
                          ...styles.td,
                          textAlign: c.type === "text" ? "left" : "right",
                          fontWeight: c.type === "total" ? 700 : 400,
                          color: c.type === "total" ? "#10243d" : "#1b2733",
                        }}
                      >
                        {cellValue(c, r)}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr>
                  {COLUMNS.map((c, i) => (
                    <td
                      key={c.key}
                      style={{
                        ...styles.tfootTd,
                        textAlign: c.type === "text" ? "left" : "right",
                      }}
                    >
                      {i === 0
                        ? "Totals"
                        : c.key === "OutstandingAmount"
                        ? fmt(totals.OutstandingAmount)
                        : fmt(totals[c.key])}
                    </td>
                  ))}
                </tr>
              </tfoot>
            </table>
          )}
        </div>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Inline styles — flat, matching the plain PDF/Excel output          */

const styles = {
    app: {
        maxWidth: 900,
        margin: "0 auto",
        padding: "20px 20px 60px",
        fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
        color: "#1b2733",
        background: "#f2f5f8",
    },
    toolbar: {
        padding: "16px 20px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 16,
        flexWrap: "wrap",
    },
    toolbarTitle: {
        color: "#fff",
        fontSize: 17,
        fontWeight: 600,
        margin: 0,
    },
    controls: { display: "flex", alignItems: "flex-end", gap: 14, flexWrap: "wrap" },
    field: { display: "flex", flexDirection: "column", gap: 4 },
    label: {
        fontSize: 10.5,
        textTransform: "uppercase",
        letterSpacing: "0.06em",
        fontWeight: 600,
    },
    input: {
        border: "1px solid #35516f",
        padding: "7px 10px",
        fontSize: 13,
        minWidth: 170,
        outline: "none",
    },
    btnPrimary: {
        border: "1px solid #35516f",
        padding: "8px 16px",
        fontSize: 13,
        fontWeight: 600,
        cursor: "pointer",
    },
    exportBar: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        margin: "16px 0 0",
        padding: "10px 4px",
        flexWrap: "wrap",
        gap: 10,
    },
    statusLine: { fontSize: 12, color: "#5b6b7b" },
    exportActions: { display: "flex", gap: 10 },
    btnExport: {
        background: "#fff",
        border: "1px solid #dde3ea",
        padding: "8px 14px",
        fontSize: 12.5,
        fontWeight: 600,
        cursor: "pointer",
    },
  sheet: {
    background: "#fff",
    marginTop: 14,
    border: "1px solid #dde3ea",
    overflowX: "auto",
},

sheetInner: { 
    padding: "24px 20px 28px" 
},    reportTitle: {
        textAlign: "center",
        fontSize: 17,
        fontWeight: 700,
        color: "#10243d",
        marginBottom: 18,
    },
    reportMeta: {
        display: "flex",
        justifyContent: "space-between",
        fontSize: 12,
        color: "#5b6b7b",
        marginBottom: 16,
    },
    table: { width: "100%", borderCollapse: "collapse", fontSize: 12.5 },
 th: {
    background: "#eaf1fb",
    color: "#10243d",
    fontWeight: 700,
    fontSize: 11.5,
    padding: "9px 10px",
    border: "1px solid #dde3ea",
    whiteSpace: "normal",
},
    td: { padding: "8px 10px", border: "1px solid #dde3ea" },
    rowAlt: { background: "#f9fbfd" },
    tfootTd: {
        padding: "11px 10px",
        border: "1px solid #dde3ea",
        borderTop: "2px solid #10243d",
        background: "#eaf1fb",
        fontWeight: 700,
        color: "#10243d",
    },
    empty: { textAlign: "center", padding: "40px 0", color: "#5b6b7b", fontSize: 13 },
};